name: Render Quarto Document

on:
  push:
    branches:
      - main  
    paths:
      - 'Digital-Ad-Campaign-Effectiveness/Digital-Ad.qmd'
      - 'New-Marketing-Strategy-Impact/New-Mkt-Impact.qmd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.183/quarto-1.1.183-linux-amd64.deb
        sudo dpkg -i quarto-1.1.183-linux-amd64.deb

    - name: Render Quarto Document
      run: quarto render Digital-Ad.qmd --to html

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.html
        git commit -m "Automatically render qmd and commit HTML" -a || echo "No changes to commit"
        git push
